### ISSUE TITLE
Add a task from anywhere

### ISSUE THREAD

**Issue by bepolymathe** [gpapp/FreePlaneGTD#114]
Hi @dpolivaev and @gpapp !

Thank you for freeplane and this excellent addon. I have a question and/or suggestion. I will find it very useful to be able to configure a global keyboard shortcut on my computer that would automatically open the task edit window. This newly created task could by default be attached to an "inbox" node. 

Is there already a way to do this? If not, would it be a good idea?

**Comment by gpapp** [comment]
There is no possibility to do such a function without major development. The results would be messy would need to break into the OSGI framework of Freeplane and hard to install. It would be hell to maintain.

FreeplaneGTD add-on is an add-on to the Freeplane, not a stand-alone program. It is running in a restricted add-on framework. It does not have the privilege to open files by itself and only works on a map that is already open. 
There is no add new task using an editor functionality in the add-on! Task editor doesn't work in standalone mode, it requires you to select a task already created by a shortcut. Otherwise it would not know where to put it in the map.

To do what you suggest would require a headless Freeplane to run as a service continuously on your computer that keeps a map open. When you open Freeplane in normal mode, this should be terminated, as it cannot keep the same file open.  Than there should be a plugin (not an add-on) installed within Freeplane, that triggers the currently non existing add new task interface. This could add a new task node under the root node of your map, but after a few dozen it will become a mess. 

If you need a functionality like this, you could use some windows desktop automation tool, that opens the freeplane window, creates a task node, then open the editor on it. I suggest looking into AutoIt (https://www.autoitscript.com/site/) that might be able to solve this problem. 

On the other hand you could use the sticky notes from Microsoft or any other fast note taking app, to keep a bulleted list of activities. Text should be pastable into Freeplane. If you stick to the shortcode format you will have these converted to tasks straight away.

Feel free to share your solution with the community!

**Comment by bepolymathe** [comment]
Thanks for reply ! 
I will check it for a solution. As linux user i need to investigate an other solution.

**Comment by dpolivaev** [comment]
@bepolymathe Freeplane can be started with the option to execute a given script and to quit. This way you can have a separate program which calls Freeplane to manipulate your maps. Currently, it is not checking if other instances are already opened with the mind map you want to change. Maybe it could be implemented on the Freeplane side so that the solution is safe also in this case. If you are strong in Java and interested to code it, let me know. But I also see this not as a part of the GTD add-on.

**Comment by bepolymathe** [comment]
Thank you for this answer. It's an interesting lead. Yes, I agree with you that it does not come from this addon. Unfortunately, I'm not good at java... 

How to launch freeplane with a given script and quit (linux) ? I will do some tests in the coming days.

**Comment by dpolivaev** [comment]
Check https://www.freeplane.org/wiki/index.php/Command-line_options_and_configuration and https://www.freeplane.org/wiki/index.php/Batch_Jobs. I am not sure if the information is up to date.

**Comment by bepolymathe** [comment]
Hi @dpolivaev , 

I made some quick test... i can launch a quick command with a shortcut that execute the following command where `ID_729892401` is the identity of my inbox node for task. 

`sh /freeplane-1.8.8/freeplane.sh -XNewChildAction -XEditLongAction /home/manu/maps/todo.mm#ID_729892401 `

Obviously it's a bit slow because you have to launch freeplane each time but it works for the moment...

**Comment by bepolymathe** [comment]
An idea @dpolivaev. Would it be possible to do this operation silently by also passing a node content into the command ?
