### ISSUE TITLE
Feature request: customizeable status of tasks and projects for kanban

### ISSUE THREAD

**Issue by weinland** [gpapp/FreePlaneGTD#55]
Hi,

I use GTD+ a lot to keep track of my projects and actions at work and I like this addon very much.
The only thing I am missing is the possibility to add a status to each task or project that is different from “done”. I tried to use the context value for that purpose but if I change the icon, the context values just stack up.
Is it possible to add another value called for example “status” which is defined by entries in the settings node (like context). In the GTD window this tab should show the tasks/projects in columns sorted by the appearance of the status in the settings node.

I hope this is possible. Keep up your good work :)

Cheers,
Tristan

**Comment by gpapp** [comment]
I'm really glad you find the add-on useful. Please keep it in mind, that this add-on is designed for GTD and not for personal Kanban. In GTD task statuses don't make much sense.

If you really need the statuses you can  implement it by either using 
* priorities, 
* dedicated contexts and icons as you mentioned,
* using the built-in property editor feature of the Freeplane, 
* using top level "Projects" to model the statuses,

Priorities are the the easiest. You just decide which priority to map to which kanban state, and use the task editor to overwrite it. If you don't use any due dates, this will line the tasks up in groups of priorities on the timeline view.

If you use the contexts, you can use the task editor to change the status, and overwrite the previous status related contexts. Since you are allowed to use multiple contexts, this would work along pretty nice with them. You'll see the tasks related to each status in the context view.

If you use the property editor, you'll be able to add a status property to the nodes, and filter them using the advanced filters available in Freeplane. This is quite simple, as FreeplaneGTD already uses the properties to store it's data. There is no visualization for this though.

If you use the top-level projects, then you just drag-and-drop the tasks from one state to another. You'll have to duplicate all your projects first to do so. You'll be able to see your status on the project view.

If you feel the need to have this feature, you can go on and implement it yourself, it's not difficult! I'm always open to accept code contributions as long as they don't break the core functionality!
