### ISSUE TITLE
Next Actions window shows strange title for archived actions

### ISSUE THREAD

**Issue by JonasPf** [gpapp/FreePlaneGTD#73]
It shows =textUtils.getText('freeplaneGTD.config.archiveDirName') as the title for archived actions.

![gtd](https://user-images.githubusercontent.com/2216775/31992772-17ff41f0-b973-11e7-81a8-aef959e1b4e7.png)

Thanks for the great work!

**Comment by gpapp** [comment]
I tested it and I know what happens. You have redefined the "Icon: Project" to the folder icon used on the archive node. Since that is defined in the core template using a macro to return a language specific string, it  will appear as the script itself in the task pane.

I've created a fix, that will be included in the next release.
