### ISSUE TITLE
Error executing the script: null

### ISSUE THREAD

**Issue by jolewis-ddn** [gpapp/FreePlaneGTD#95]
I have a very simple mm file
[bug20190419.zip](https://github.com/gpapp/FreePlaneGTD/files/3099423/bug20190419.zip)

Steps to reproduce:
1. Install the latest FreeplaneGTD (2.0.1) with Freeplane 1.7.7
2. Open the simple mm file
3. Click Ctrl-H
4. Always returns this error:
![image](https://user-images.githubusercontent.com/31732476/56445977-eb7a7680-62cd-11e9-8f30-2e10aaaac2d3.png)

Log file:
[error20190419.log](https://github.com/gpapp/FreePlaneGTD/files/3099418/error20190419.log)

(a lot of `unable to resolve class` errors)

Separately, I tried [freeplaneGTD-v2.1.1-alpha4.addon.mm](https://github.com/gpapp/FreePlaneGTD/releases/download/v2.1-alpha-4/freeplaneGTD-v2.1.1-alpha4.addon.mm) - same error dialog.
Tried [FreeplaneGTD+ v1.9.3](https://www.itworks.hu/freeplanegtd-release/freeplaneGTD-v1.9.3.addon.mm) - same error dialog.
Tried [freeplaneGTD-v0.8.1.addon.mm](https://sourceforge.net/projects/freeplanegtd/files/) - works fine.

**Comment by gpapp** [comment]
Bad news, Oracle removed the JavaFX support from the latest JRE. 

The browser component is no longer available to display the task list.

I'll look into installing the JavaFX library from the addon. 

It should be added to the freeplane class path somehow.

**Comment by bepolymathe** [comment]
Any news about this ?

**Comment by gpapp** [comment]
I don't have a working development environment, and this requires major hacking of the Freeplane and the JRE classloader and the Groovy security module. I've hacked it twice already, but that takes too much time and is fragile.
It would probably be best to rewrite it in pure Swing instead of the browser component. That again requires development environment and time.

**Comment by tylla** [comment]
@jolewis-ddn I suppose you're using Freeplane on Windows, but for those running it on Linux, the solution is to install OpenJFX. Eg. under Debian I typed `sudo apt-get install openjfx` and restarted Freeplane just for sure.

**Comment by gpapp** [comment]
@tylla the error log shows Windows 10 with Oracle Java 11 which doesn't have JavaFX anymore. I have no idea how to add JavaFX on the new pluggable JRE in Windows.

**Comment by RuubixO** [comment]
@tylla @gpapp I'm running GTD+ addon with Freeplane 1.7.9 (installed from the zip file to my home directory) and was getting the same error message as in the duplicated issue linked to this thread.
I did the OpenFX install `sudo dnf install openjfx` command. Restarted freeplane, but I'm getting the same error messages.
tylla, can you confirm which version of OpenJFX worked for you?

**Comment by gpapp** [comment]
There is no sensible way of getting the Freeplane OSGI framework play nice with JavaFX. It requires modification of adding libraries to the runner, editing starting scripts, depending the OS version, flavor and freeplane's distribution. The addon is supposed to work on it's own after installation.

The only fix is to rewrite the tasklist ___again___. This is the third and last time since I started working on keeping the addon alive. Flyingsaucer libs needed security hacking in the core, to add nice colored lists and icons, JavaFX was added to add clickable tasks and buttons, now we are tripping back 20 years to use Swing again. Once it's stabilized I'll be giving up on this project.

The initial release is available here:
https://github.com/gpapp/FreePlaneGTD/releases/tag/v3.0-alpha1

Enjoy!

**Comment by dartrax** [comment]
I'm still having this issue, tried alpha1 and alpha2. Do I need a newer Freeplane Version?
Log:

[log0.txt](https://github.com/gpapp/FreePlaneGTD/files/4026637/log0.txt)
[log1.txt](https://github.com/gpapp/FreePlaneGTD/files/4026647/log1.txt)
[log2.txt](https://github.com/gpapp/FreePlaneGTD/files/4026656/log2.txt)
[log3.txt](https://github.com/gpapp/FreePlaneGTD/files/4026654/log3.txt)

**Comment by gpapp** [comment]
Please remove the add-on from the application and all its dangling files under your profile. Then try to install the 3.5.0-alpha2 from https://github.com/gpapp/FreePlaneGTD/releases

**Comment by dartrax** [comment]
Ok so I uninstalled the add-on via Add-Ons-Manager, restarted Freeplane, closed Freeplane, went to the user-folder `C:\Users\traxel\AppData\Roaming\Freeplane\1.7.x` (is that the one you mean?), deleted everything gtd-related I could found (especially within addons and lib folder), install 3.5.0-alpha2 again by opening the .mm-file, restart Freeplane, tried again.
Unfortunately, same error.

[log.0.1.txt](https://github.com/gpapp/FreePlaneGTD/files/4027277/log.0.1.txt)
[log.0.txt](https://github.com/gpapp/FreePlaneGTD/files/4027278/log.0.txt)
[log.1.txt](https://github.com/gpapp/FreePlaneGTD/files/4027279/log.1.txt)
[log.2.txt](https://github.com/gpapp/FreePlaneGTD/files/4027280/log.2.txt)
[log.3.txt](https://github.com/gpapp/FreePlaneGTD/files/4027281/log.3.txt)
[log.4.txt](https://github.com/gpapp/FreePlaneGTD/files/4027282/log.4.txt)

**Comment by gpapp** [comment]
It seems like this version is not compatible with the add-on. Switch to a later version of freeplane.

**Comment by dartrax** [comment]
I called the IT department because I have not the rights to do that. We tested with freeplane 1.7.10 and several different versions of the GTD Plugin, getting Errors like that:
![Fehler mit 3 5 Alpha 2 Addon](https://user-images.githubusercontent.com/15105943/71908915-292a7280-316f-11ea-8771-f26ecf33d909.png)
![Fehler mit 2 0 1 Addon](https://user-images.githubusercontent.com/15105943/71908918-292a7280-316f-11ea-9f1f-984d1ad5d9e0.png)

It turned out that the problem was the version of Java that was installed by our IT. Because of changes to the license agreement, IT decided to switch to the Java SE Development Kit. Freeplane works with that, but obviously not GTD. We tested 12.0.1 and 12.0.2 of the JDK. After that we switched back to standard java (Java 8 Update 221). GTD still did not work. After an update to Java 8 Update 231, GDT finally worked again!

I can submit a feature request for compatibility with the Java SE Development Kit if that's not too unlikely?

**Comment by gpapp** [comment]
I just tested Java SE Development kit v13, it has an upstream error, that causes a Groovy exception that originates from the Groovy compiler itself. 
"General error during semantic analysis: Unsupported class file major version 57" basically means it cannot run the classes compiled by Freeplane itself.

**Comment by dartrax** [comment]
So should the bug report go to freeplane or JDK? (If there isn't one already, of course)

**Comment by DavidEnergie** [comment]
Freeplane 1.7.10
Java 1.8.0_241
FreeplaneGTD 3.5.0-alpha2
------------------------------------------------------------------
After using Windows 10 for two weeks at my employer, I ran into this same issue, when trying to convert the tasks. 

"Error executing script:
Cannot invoke method getGtdReportControllerClass() on null object"

I will finally take some time to move to Linux at work. Thanks for the solution @RuubixO 

And thanks for all the good work on this amazing plugin @gpapp !!! :-)

[20200206_Freeplane_GTD-error_log.0.txt](https://github.com/gpapp/FreePlaneGTD/files/4165395/20200206_Freeplane_GTD-error_log.0.txt)
